name: Check builds
on:
  - push
  - pull_request

jobs:
  run-darwin-tests:
    name: Run tests on Darwin
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64
        channel:
          - nixpkgs-stable-darwin
        branch:
          - next

        # Define architecture values according to the runner in use.
        include:
          - arch: aarch64
            runner: macos-latest
            cache-system: ARM64-macOS

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v20
      - name: Set up Nix caching
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check system
        env:
          TARGET_SYSTEM: ${{ matrix.arch }}-darwin
        run: |
          current_system="$(nix eval --impure --raw --expr builtins.currentSystem)"
          if [[ "$current_system" != "$TARGET_SYSTEM" ]]; then
              printf '::error title=System mismatch::Running on %s, expected %s\n' "$current_system" "$TARGET_SYSTEM"
              exit 1
          fi
      - name: Run checks
        timeout-minutes: 345
        env:
          CHANNEL: ${{ matrix.channel }}
          TARGET_SYSTEM: ${{ matrix.arch }}-darwin
          BRANCH: ${{ matrix.branch }}
        run: |
          tmpdir="$(mktemp -d)"
          nix eval --json --apply builtins.attrNames .#checks."$TARGET_SYSTEM" >"$tmpdir"/checkattrs
          # Escaping here based on lib.strings.escapeNixIdentifier
          jq --raw-output '.[]
              | select(endswith("-\($ENV.BRANCH)-\($ENV.CHANNEL)"))
              | ["checks", $ENV.TARGET_SYSTEM, .]
              | map(
                  if test("^[a-zA-Z_][a-zA-Z0-9_'\''-]*$")
                  then .
                  else @json | gsub("\\$"; "\\$")
                  end
                  )
              | join(".")
              | ".#" + .
          ' >"$tmpdir"/checktargets <"$tmpdir"/checkattrs
          nix build --stdin --keep-going <"$tmpdir"/checktargets
