name: Check builds
on:
  - push
  - pull_request

jobs:
  run-tests:
    name: Run tests
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-latest
          - ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Recover runner disk space
        uses: wimpysworld/nothing-but-nix@v10
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22
      - name: Set up Nix caching
        uses: me-and/magic-nix-cache-action@restore-only
        with:
          save-cache: ${{ github.ref == 'refs/heads/main' }}
      - name: Run checks
        timeout-minutes: 345
        run: nix flake check

  fmt:
    name: Check formatting and evaluation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22
      - name: Set up Nix caching
        uses: me-and/magic-nix-cache-action@restore-only
        with:
          save-cache: ${{ github.ref == 'refs/heads/main' }}
      - name: Check formatting
        run: nix fmt -- --ci
      - name: Check evaluation
        run: nix flake check --no-build --all-systems --keep-going
