name: Update Git version
on:
  schedule:
    # Randomly selected, 30 minutes offset from updating the Flake
    - cron: '44 * * * *'
  workflow_dispatch:

jobs:
  update-versions:
    name: Update Git
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.COMMIT_PUSH_PAT }}
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
      - name: Set up Nix caching
        uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          source-url: https://github.com/jchw-forks/magic-nix-cache/releases/download/nightly/magic-nix-cache-X64-Linux
      - name: Update Git version
        env:
          GIT_AUTHOR_EMAIL: actions@github.com
          GIT_AUTHOR_NAME: GitHub Actions
          GIT_COMMITTER_EMAIL: actions@github.com
          GIT_COMMITTER_NAME: GitHub Actions
        run: nix run .#updateScript -- -c
      - name: Push changes
        run: git push
