name: Update Flake
on:
  schedule:
    # Randomly selected, 12 hours offset from updating Git
    - cron: '14 20 * * *'
  workflow_dispatch:

jobs:
  update-versions:
    name: Update Flake
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
      - name: Update inputs
        run: nix flake update --commit-lock-file
      - name: Push changes
        run: git push
