name: Update Git version
on:
  schedule:
    # Randomly selected, 30 minutes offset from updating the Flake
    - cron: '44 * * * *'
  workflow_dispatch:

concurrency: commit-${{ github.ref }}

jobs:
  update-versions:
    name: Update Git
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.COMMIT_PUSH_PAT }}
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v19
      - name: Set up Nix caching
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Update Git version
        env:
          GIT_AUTHOR_EMAIL: actions@github.com
          GIT_AUTHOR_NAME: GitHub Actions
          GIT_COMMITTER_EMAIL: actions@github.com
          GIT_COMMITTER_NAME: GitHub Actions
        run: nix run .#updateScript -- -c
      - name: Push changes
        run: git push
